name: autofarmer
description: A smart farming solution
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  provider: ^6.0.5
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  archive: ^3.4.9
  barcode_scan2: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
