name: autofarmer
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase + Plugins
  firebase_core: ^2.15.1
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.10.3

  # QR Scanner
  qr_code_scanner: ^1.0.1

  # State Management
  provider: ^6.1.1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
